manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: krikun98
      url-base: https://github.com/krikun98
    - name: ftc
      url-base: https://github.com/ftc
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk-mouse
      remote: ftc
      revision: mouse-ftc
      import: app/west.yml    
    - name: zmk-splitkb
      remote: petejohanson
      revision: shields/splitkb_aurora_sweep
      import: app/west.yml
  self:
    path: config
